# Generated by Django 2.2.3 on 2023-03-18 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50)),
                ('exterior', models.CharField(max_length=50)),
                ('interior', models.CharField(max_length=50)),
                ('neighborhood', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('municipality', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=50)),
                ('tax_id', models.CharField(max_length=50)),
                ('tax_system', models.CharField(max_length=3)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('is_create', models.BooleanField(default=False)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturaP.address')),
            ],
        ),
        migrations.CreateModel(
            name='empresa',
            fields=[
                ('legal_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('numero', models.PositiveSmallIntegerField()),
                ('fechaCotizacion', models.CharField(max_length=6)),
                ('fechaPedido', models.CharField(max_length=6)),
                ('tipoVenta', models.CharField(max_length=6)),
                ('moneda', models.CharField(max_length=6)),
                ('nombreVendedor', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='local_taxes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('rate', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='taxes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('rate', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('product_key', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('tax_included', models.BooleanField(default=False)),
                ('taxability', models.BooleanField(default=False)),
                ('unit_key', models.CharField(max_length=200)),
                ('unit_name', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=200)),
                ('local_taxes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturaP.local_taxes')),
                ('taxes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturaP.taxes')),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=200)),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturaP.producto')),
            ],
        ),
        migrations.CreateModel(
            name='factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=3)),
                ('payment_form', models.CharField(max_length=200)),
                ('folio_number', models.CharField(max_length=200)),
                ('series', models.CharField(max_length=200)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturaP.cliente')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturaP.item')),
            ],
        ),
    ]
